function getCart(){try{return JSON.parse(localStorage.getItem('supleagi_cart')||'[]')}catch(e){return[]}}
function saveCart(c){localStorage.setItem('supleagi_cart',JSON.stringify(c));updateCount();window.dispatchEvent(new Event('cart:updated'))}
function addToCart(name,price,qty=1){const c=getCart();const x=c.find(i=>i.name===name);x?x.qty+=qty:c.push({name,price,qty});saveCart(c);toast(name+' — dodano do koszyka')}
function toast(msg){const t=document.getElementById('cart'),cta=document.getElementById('toastText');if(!t)return;if(cta)cta.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function updateCount(){const n=getCart().reduce((a,i)=>a+i.qty,0);document.querySelectorAll('#cartCount').forEach(x=>x.textContent=n);const w=JSON.parse(localStorage.getItem('supleagi_wishlist')||'[]').length;document.querySelectorAll('#wishCount').forEach(x=>x.textContent=w)}
function addBundle(){const c=getCart();const x=c.find(i=>i.name==='Whey + Creatine — Zestaw');x?x.qty++:c.push({name:'Whey + Creatine — Zestaw',price:179,qty:1});saveCart(c);toast('Zestaw — dodano do koszyka')}
function changeQty(n,d){const c=getCart();if(!c[n])return;c[n].qty+=d;if(c[n].qty<=0)c.splice(n,1);saveCart(c);renderCart()}
function filterProducts(cat,btn){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.product-item').forEach(x=>x.style.display=cat==='all'||x.dataset.cat===cat?'block':'none')}
function renderCart(){updateCount();const box=document.getElementById('cartItems'),c=getCart();if(!c.length){box.innerHTML='<div class="cart-row"><span class="muted">Koszyk jest pusty.</span><a class="btn primary" href="shop.html">Przejdź do sklepu</a></div>';['subtotal','total'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='0,00 zł'});return}
box.innerHTML=c.map((i,n)=>'<div class="cart-row"><div class="cart-product"><div class="cart-thumb">SA</div><div><b>'+i.name+'</b><div class="muted">'+i.price.toFixed(2).replace('.',',')+' zł / szt.</div></div></div><div class="cart-controls"><div class="qty"><button onclick="changeQty('+n+',-1)">−</button><b>'+i.qty+'</b><button onclick="changeQty('+n+',1)">+</button></div><b>'+(i.price*i.qty).toFixed(2).replace('.',',')+' zł</b><button class="remove" onclick="removeItem('+n+')">Usuń</button></div></div>').join('');
const subtotal=c.reduce((a,i)=>a+i.price*i.qty,0),free=199,ship=subtotal>=free?0:14.99,total=subtotal+ship;document.getElementById('subtotal').textContent=subtotal.toFixed(2).replace('.',',')+' zł';document.getElementById('shipping').textContent=ship?ship.toFixed(2).replace('.',',')+' zł':'GRATIS';document.getElementById('total').textContent=total.toFixed(2).replace('.',',')+' zł';const missing=Math.max(0,free-subtotal),bar=document.getElementById('freeShipBar');if(bar)bar.style.width=Math.min(100,subtotal/free*100)+'%';const msg=document.getElementById('freeShipText');if(msg)msg.textContent=missing?'Brakuje Ci '+missing.toFixed(2).replace('.',',')+' zł do darmowej dostawy 🚚':'Darmowa dostawa została odblokowana 🚚'}
function removeItem(n){const c=getCart();c.splice(n,1);saveCart(c);renderCart()}
function renderCheckout(){updateCount();const c=getCart();const box=document.getElementById('checkoutItems');if(box)box.innerHTML=c.map(i=>'<div class="sumrow"><span>'+i.name+' × '+i.qty+'</span><b>'+(i.price*i.qty).toFixed(2).replace('.',',')+' zł</b></div>').join('');const total=c.reduce((a,i)=>a+i.price*i.qty,0);const el=document.getElementById('checkoutTotal');if(el)el.textContent=total.toFixed(2).replace('.',',')+' zł'}
function placeOrder(e){e.preventDefault();localStorage.removeItem('supleagi_cart');document.body.innerHTML='<main class="wrap" style="padding-top:120px;text-align:center"><div class="eyebrow">Sukces</div><h1 style="font-size:70px;letter-spacing:-4px">Zamówienie<br><em>przyjęte.</em></h1><p class="muted">To demo — płatność nie została pobrana.</p><a class="btn primary" href="index.html">Wróć na stronę główną</a></main>'}
const searchProducts=[['Whey Protein',129],['Whey Protein Vanilla',129],['Creatine',69],['Daily Vitamins',49],['Pre-Workout',89],['Omega 3',59]];
function openSearch(){const o=document.getElementById('searchOverlay');if(o){o.classList.add('open');setTimeout(()=>document.getElementById('searchInput')?.focus(),50)}}
function closeSearch(){document.getElementById('searchOverlay')?.classList.remove('open')}
function searchHome(){const q=(document.getElementById('searchInput')?.value||'').toLowerCase(),box=document.getElementById('searchResults');if(!box)return;box.innerHTML=searchProducts.filter(p=>p[0].toLowerCase().includes(q)).map(p=>'<div class="search-result"><span><b>'+p[0]+'</b><br><small>'+p[1]+',00 zł</small></span><button onclick="addToCart(\''+p[0]+'\','+p[1]+')">Dodaj</button></div>').join('')||'<p class="muted">Brak wyników.</p>'}
updateCount();